### ISSUE TITLE
Разработка конфигуратора

### ISSUE THREAD

**Issue by egorsh0** [alfa-laboratory/AlfaBank.AFT.Core.Library#54]
При работе с одними и теми же сценариями появляется возможность использовать их на разных стендах и средах
В данный момент реализация сделана по json файлу aft.config.json
Example:
`
{
  "reports": [ "ReportPortal" ],
  "parameters": [
    {
      "name": "WebService",
      "params": {
        "auth_login": "test_login",
        "auth_pass": "test_pass"
      }
    }]
}
`
В чем суть:

- явная привязка к json файлу
- распределение по Tags (каждый name в json это Tag)
- привязка к reportportal

Что необходимо сделать:

- посмотреть что лучше: json или ini (мб сделать реализацию на ini файлах)
- В данный момент все переменные создаются в тот же словарь, что и VariableContext. Предложение в Variable добавить поле "Тип доступа" с enum
Варианты: глобальная и локальная
локальная - переменная, созданная в сценарии. Глобальная - взятая из конфига.
Приоритеты: при получении значения из переменной идет проверка - есть ли переменная с глобальным типом. Если есть, то взять значение из него. Если нет - из локальной. Выдавать в логер какое значение и откуда было взято
- добавить предсоздание файла с default переменными при подключении библиотеки

**Comment by Fufelhmertz** [comment]
Взял
